
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 12 13:15:47 VET 2018
//----------------------------------------------------

package Tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int READ = 8;
  public static final int OVER = 19;
  public static final int LT = 14;
  public static final int ELSE = 4;
  public static final int PLUS = 16;
  public static final int RPAREN = 21;
  public static final int THEN = 3;
  public static final int SEMI = 25;
  public static final int RETURN = 24;
  public static final int END = 5;
  public static final int IF = 2;
  public static final int LPAREN = 20;
  public static final int GT = 15;
  public static final int WRITE = 9;
  public static final int ID = 10;
  public static final int RCOR = 23;
  public static final int NUM = 11;
  public static final int LCOR = 22;
  public static final int EOF = 0;
  public static final int MINUS = 17;
  public static final int error = 1;
  public static final int UNTIL = 7;
  public static final int ASSIGN = 12;
  public static final int EQ = 13;
  public static final int VOID = 26;
  public static final int REPEAT = 6;
}

